const courts = [
  {
    id: 1,
    name: "DLF Cyber City Pickleball Club",
    area: "Gurgaon",
    locality: "Cyber City / DLF Phase 2",
    address: "DLF Cyber City, Sector 24, Gurugram, Haryana 122002",
    type: "indoor",
    courts: 4,
    surface: "Synthetic",
    pricePerHour: 600,
    peakHours: ["6:00 AM - 9:00 AM", "5:00 PM - 9:00 PM"],
    offPeakHours: ["9:00 AM - 5:00 PM"],
    offPeakPrice: 400,
    amenities: ["Changing rooms", "Equipment rental", "Coaching available", "Parking"],
    phone: "+91-98110-00001",
    rating: 4.5,
    reviewCount: 128,
    levelSuitable: ["beginner", "intermediate", "advanced"],
    coachingAvailable: true,
    monthlyMembership: 3500,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:00 AM - 10:00 PM",
    nearbyMetro: "MG Road (10 min)",
    notes: "Best for corporate players. Peak time 7-9 AM with office goers."
  },
  {
    id: 2,
    name: "Noida Sports Complex Pickleball Arena",
    area: "Noida",
    locality: "Sector 21",
    address: "Sector 21 Sports Complex, Noida, UP 201301",
    type: "outdoor",
    courts: 6,
    surface: "Acrylic hardcourt",
    pricePerHour: 400,
    peakHours: ["6:00 AM - 9:00 AM", "4:00 PM - 8:00 PM"],
    offPeakHours: ["9:00 AM - 4:00 PM"],
    offPeakPrice: 250,
    amenities: ["Floodlights", "Parking", "Cafeteria", "Equipment rental"],
    phone: "+91-98110-00002",
    rating: 4.2,
    reviewCount: 89,
    levelSuitable: ["beginner", "intermediate", "advanced"],
    coachingAvailable: true,
    monthlyMembership: 2500,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:00 AM - 9:00 PM",
    nearbyMetro: "Sector 18 (15 min auto)",
    notes: "Large community of intermediate players. Sunday mornings have open play."
  },
  {
    id: 3,
    name: "South Delhi Pickleball Hub",
    area: "South Delhi",
    locality: "Vasant Kunj",
    address: "Vasant Kunj Sports Village, New Delhi 110070",
    type: "indoor",
    courts: 3,
    surface: "Synthetic wood",
    pricePerHour: 700,
    peakHours: ["6:30 AM - 9:30 AM", "6:00 PM - 9:00 PM"],
    offPeakHours: ["9:30 AM - 6:00 PM"],
    offPeakPrice: 450,
    amenities: ["AC facility", "Locker rooms", "Pro shop", "Coaching", "Cafe"],
    phone: "+91-98110-00003",
    rating: 4.7,
    reviewCount: 214,
    levelSuitable: ["intermediate", "advanced", "competitive"],
    coachingAvailable: true,
    monthlyMembership: 4500,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:30 AM - 10:00 PM",
    nearbyMetro: "Vasant Vihar (5 min)",
    notes: "Premium facility. Home to several state-level players. Great for competitive players."
  },
  {
    id: 4,
    name: "Faridabad Recreation Center",
    area: "Faridabad",
    locality: "NIT Faridabad",
    address: "Recreation Ground, NIT Sector 15, Faridabad, Haryana 121001",
    type: "outdoor",
    courts: 4,
    surface: "Concrete",
    pricePerHour: 200,
    peakHours: ["7:00 AM - 10:00 AM", "4:00 PM - 7:00 PM"],
    offPeakHours: ["10:00 AM - 4:00 PM"],
    offPeakPrice: 120,
    amenities: ["Parking", "Washrooms", "Basic equipment rental"],
    phone: "+91-98110-00004",
    rating: 3.8,
    reviewCount: 42,
    levelSuitable: ["beginner", "intermediate"],
    coachingAvailable: false,
    monthlyMembership: 1200,
    bookingLink: "#",
    openDays: "Tue-Sun",
    timing: "7:00 AM - 8:00 PM",
    nearbyMetro: "Faridabad (20 min auto)",
    notes: "Budget-friendly. Great for beginners. Growing pickleball community."
  },
  {
    id: 5,
    name: "West Delhi Pickleball Courts",
    area: "West Delhi",
    locality: "Janakpuri",
    address: "Janakpuri Sports Complex, Block C, New Delhi 110058",
    type: "indoor",
    courts: 2,
    surface: "Synthetic",
    pricePerHour: 500,
    peakHours: ["6:00 AM - 9:00 AM", "5:00 PM - 8:00 PM"],
    offPeakHours: ["9:00 AM - 5:00 PM"],
    offPeakPrice: 300,
    amenities: ["Parking", "Changing rooms", "Coaching"],
    phone: "+91-98110-00005",
    rating: 4.1,
    reviewCount: 67,
    levelSuitable: ["beginner", "intermediate"],
    coachingAvailable: true,
    monthlyMembership: 3000,
    bookingLink: "#",
    openDays: "Mon-Sat",
    timing: "6:00 AM - 9:00 PM",
    nearbyMetro: "Janakpuri West (5 min)",
    notes: "Good for beginners. Coach available weekday mornings."
  },
  {
    id: 6,
    name: "Greater Noida Pickleball Club",
    area: "Greater Noida",
    locality: "Sector Omega 1",
    address: "Alpha Sports Hub, Greater Noida, UP 201310",
    type: "outdoor",
    courts: 5,
    surface: "Acrylic",
    pricePerHour: 300,
    peakHours: ["6:00 AM - 9:00 AM", "4:00 PM - 7:00 PM"],
    offPeakHours: ["9:00 AM - 4:00 PM"],
    offPeakPrice: 180,
    amenities: ["Parking", "Cafeteria", "Equipment rental", "Floodlights"],
    phone: "+91-98110-00006",
    rating: 4.3,
    reviewCount: 53,
    levelSuitable: ["beginner", "intermediate", "advanced"],
    coachingAvailable: true,
    monthlyMembership: 2000,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:00 AM - 9:30 PM",
    nearbyMetro: "Pari Chowk (15 min auto)",
    notes: "Fast-growing club. Weekend tournaments every month."
  },
  {
    id: 7,
    name: "Dwarka Sports Village",
    area: "Dwarka",
    locality: "Sector 10 Dwarka",
    address: "Sports Village, Sector 10, Dwarka, New Delhi 110075",
    type: "indoor",
    courts: 3,
    surface: "Vinyl",
    pricePerHour: 550,
    peakHours: ["6:30 AM - 9:30 AM", "5:30 PM - 9:00 PM"],
    offPeakHours: ["9:30 AM - 5:30 PM"],
    offPeakPrice: 350,
    amenities: ["AC", "Parking", "Locker rooms", "Coaching", "Water station"],
    phone: "+91-98110-00007",
    rating: 4.4,
    reviewCount: 91,
    levelSuitable: ["beginner", "intermediate", "advanced"],
    coachingAvailable: true,
    monthlyMembership: 3200,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:30 AM - 10:00 PM",
    nearbyMetro: "Dwarka Sector 10 (5 min)",
    notes: "Very popular with families. Has beginner clinics on Saturdays."
  },
  {
    id: 8,
    name: "Gurgaon Golf & Sports Club (Pickleball Wing)",
    area: "Gurgaon",
    locality: "Sector 15",
    address: "Golf Course Road, Sector 15, Gurugram 122001",
    type: "indoor",
    courts: 6,
    surface: "Professional synthetic",
    pricePerHour: 900,
    peakHours: ["6:00 AM - 9:00 AM", "5:00 PM - 9:00 PM"],
    offPeakHours: ["9:00 AM - 5:00 PM"],
    offPeakPrice: 600,
    amenities: ["Premium locker rooms", "Restaurant", "Pro shop", "Certified coaching", "Video analysis"],
    phone: "+91-98110-00008",
    rating: 4.8,
    reviewCount: 176,
    levelSuitable: ["intermediate", "advanced", "competitive"],
    coachingAvailable: true,
    monthlyMembership: 7500,
    bookingLink: "#",
    openDays: "Mon-Sun",
    timing: "6:00 AM - 11:00 PM",
    nearbyMetro: "IFFCO Chowk (10 min)",
    notes: "Best facility in NCR. AIPA-certified coaches. Hosts national qualifiers."
  }
];

const upcomingEvents = [
  {
    id: 1,
    name: "Delhi NCR Open Pickleball Championship",
    date: "2026-06-28",
    venue: "South Delhi Pickleball Hub, Vasant Kunj",
    type: "tournament",
    levels: ["intermediate", "advanced", "competitive"],
    registrationFee: 800,
    prizePool: "₹50,000",
    registrationDeadline: "2026-06-20",
    contact: "delhiopen@pickleballncr.in",
    description: "Annual open championship with singles and doubles categories. AIPA ranked event."
  },
  {
    id: 2,
    name: "Beginner's Pickleball Clinic — Gurgaon",
    date: "2026-06-15",
    venue: "DLF Cyber City Pickleball Club",
    type: "clinic",
    levels: ["beginner", "never_played"],
    registrationFee: 500,
    prizePool: null,
    registrationDeadline: "2026-06-13",
    contact: "coach@dlfsportsclub.in",
    description: "3-hour crash course covering rules, basic strokes, and strategy. Equipment provided."
  },
  {
    id: 3,
    name: "Corporate Pickleball League — Season 3",
    date: "2026-07-05",
    venue: "Multiple venues across NCR",
    type: "league",
    levels: ["beginner", "intermediate"],
    registrationFee: 2000,
    prizePool: "Trophies + corporate sponsorships",
    registrationDeadline: "2026-06-25",
    contact: "league@pickleballncr.in",
    description: "6-week corporate team league. Bring your office team of 4. Fun and competitive!"
  },
  {
    id: 4,
    name: "Women's Doubles Invitational",
    date: "2026-06-22",
    venue: "Gurgaon Golf & Sports Club",
    type: "tournament",
    levels: ["intermediate", "advanced"],
    registrationFee: 600,
    prizePool: "₹20,000",
    registrationDeadline: "2026-06-18",
    contact: "womensopen@pickleballncr.in",
    description: "Annual women's doubles tournament. All skill levels welcome with separate brackets."
  }
];

module.exports = { courts, upcomingEvents };
